Jumpi96/helpo

- README.md
Gonzalo se equivocó al escribir el nombre de la bd. Yo lo he corregido
> Arreglo Readme

- README.md
- circle.yml
Agregada configuracion para que indique la cobertura de testing de la app en Python.
> Agregado test coverage para helpo-web

- circle.yml
Ahora sí, mira que lindo ese 68% de cobertura (?)
> 2do intento de build con code coverage

- README.md
Todo el step-by-step a la hora de laburar con Git, terminado. Es casi imposible hacer algo mal con esta wiki
> README: Instrucciones Git listas

- README.md
- docker-compose.yml
> Solucionado problema migrations de Django con Docker

- helpo-mobile/App.js
- helpo-mobile/package-lock.json
- helpo-mobile/package.json
- helpo-mobile/src/actividades/Actividades.js
- helpo-mobile/src/actividades/ActividadesCSS.js
- helpo-mobile/src/actividades/RegistrarEvento/RegistrarEvento.js
- helpo-mobile/src/actividades/RegistrarEvento/RegistrarEventoCSS.js
- helpo-web/src/actividades/Actividades.js
- helpo-web/src/actividades/RegistrarEvento/RegistrarEvento.js
- helpo-web/src/actividades/RegistrarEvento/SelectorUbicacion/SelectorUbicacion.js
- helpo-web/src/actividades/RegistrarEvento/SelectorUbicacion/SelectorUbicacion.test.js
- helpo-web/src/common.js
- helpo-web/src/env.json
-Agregado router a la app mobile.
-Para evitar poner "localhost:8000" en cada llamado a la API armé solución con un archivo env.JSON, para poder cambiarlo cuando va a producción sin tener que cambiar cada llamado del proyecto.
> Router en helpo-mobile + env apiURL

- helpo-mobile/src/actividades/Actividades.js
- helpo-mobile/src/actividades/RegistrarEvento/RegistrarEvento.js
- helpo-mobile/src/actividades/RegistrarEvento/SelectorUbicacion/SelectorUbicacion.js
- helpo-web/src/actividades/RegistrarEvento/RegistrarEvento.js
Tests:
-El sistema debe permitir ingresar ubicación escrita en un cuadro de texto.
-El sistema debe permitir ingresar una ubicación en un mapa.
-El sistema debe permitir ingresar ambas opciones antes nombradas.
-El sistema debe guardar una ubicación por defecto si la ONG no la ingresa
> US-006 -  Registrar ubicación de un evento

- ISSUE_TEMPLATE.md
- PULL_REQUEST_TEMPLATE.md
New Templates!!
- PR Template
- Issue Template
So freaking awesome templates my dearest friend
Issue #69 
By this PR, that's why I'm using all text areas
I don't want to break your display
> Added PR and Issues templates

- README.md
- Updates at README.md file
- and just testing new PR template 👍 
Adding Docker tweaks
> Updating README.md with Docker tweaks

- README.md
- docker-compose.yml
- helpo-api/Dockerfile
- helpo-api/wait-for-it.sh
- helpo-web/Dockerfile
- pgadmin.yml
- Node and Postgre Alpine images to reduce size
- python:3.6-alpine did not work, and it is not a good idea to rely on an unofficial image
- Included a script to make helpo-api wait for postgres to be ready
- Removed pgAdmin from docker-compose.yml
- if you need it make `docker-compose -f docker-compose.yml -f pgadmin.yml up
`
- Several tweaks on docker-compose.yml
Deploying 50 times all the containers
> Docker improvements: Alpine images and start up control

- helpo-web/src/views/Actividades/RegistrarEvento/RegistrarEvento.js
> e de Email

- helpo-web/src/views/Actividades/RegistrarNecesidades/RegistrarNecesidades.js
- helpo-web/src/views/Pages/Register/ModalRegistroExitoso.js
- helpo-web/src/views/Pages/Register/Register.js
Se solucionaron problemas con SignUp, provisoriamente se va mostrar una alerta para confirmar registro exitoso, hasta que se logre que funcione un nuevo modal para avisar sobre un registro exitoso en el sistema.
-
-
-
> Fixes sign up log in

- helpo-web/src/views/Perfiles/ConsultarPerfilGenerico.js
> Fix perfiles - Llamaba mal a la api

- helpo-web/src/containers/DefaultLayout/DefaultFooter.js
- helpo-web/src/containers/NoAuthLayout/NoAuthFooter.js
- helpo-web/src/views/Actividades/ConsultarEventos/ConsultarEventosList.js
- helpo-web/src/views/Actividades/MisColaboraciones/EventoPage.js
- helpo-web/src/views/Home/Home.css
- helpo-web/src/views/Home/HomeNoAuth.css
- Tamaño de imagenes
-Pies de pagina
- Mis colaboraciones en titulo
-
-
-
> Bugs varios

- helpo-api/actividades/serializers.py
- helpo-api/users/models.py
- helpo-api/users/serializers.py
- helpo-api/users/views.py
- helpo-web/package.json
- helpo-web/src/App.js
- helpo-web/src/api/eventoApi.js
- helpo-web/src/views/Actividades/ConsultarColaboraciones/ConsultarColaboraciones.js
- helpo-web/src/views/Actividades/ConsultarColaboraciones/TablaColaboraciones/FilaColaboracion.js
- helpo-web/src/views/Actividades/ConsultarColaboraciones/TablaColaboraciones/TablaColaboracion.js
- helpo-web/src/views/Actividades/ConsultarColaboraciones/TablaColaboraciones/TablaColaboraciones.js
- helpo-web/src/views/Perfiles/PerfilEmpresa/ModificarPerfilEmpresa.js
- helpo-web/src/views/Perfiles/PerfilOrganizacion/ModificarPerfilOrganizacion.js
- helpo-web/src/views/Perfiles/PerfilVoluntario/ModificarPerfilVoluntario.js
> Agregue Redux dev tools

- README.md
> Agregue link a extension de chrome (reduxDevTools)

- .gitignore
- docker-compose.aws.yml
- helpo-web/nginx.conf
- helpo-web/prod.Dockerfile
Adding pgadmin to production using AWS Compose
- Modified AWS Compose file to include a new **safe** pgAdmin 4 image
- Modified Nginx config file to redirect db.helpo.com.ar requests to pgadmin container
- Everything is SSL secured (marca registrada de Gon a esta altura)
I'm testing it at AWS while CI runs
> Adding dpage/pgadmin4 to AWS compose

- .circleci/config.yml
JPL closed my previous PR too quickly, I wanted to get a 10
- Changed docker images for even faster building and testing at CircleCI
At CircleCI
> Optimizing CircleCI 2.0

- README.md
Added debbuger setup to readme
-
-
-
Previewed readme
> Added debugger setup to vscode

- README.md
Updating helpo-mobile info at README.md
- README.md at `helpo/`
Using VSCode Markdown Preview
> Updating helpo-mobile info at README.md

- .gitignore
- docker-compose.yml
- helpo-api/helpo/settings/base.py
- helpo-mobile/App/api.js
Please **create a new folder at helpo root with name `pgadmin`**
- Defining default API-mobile communication
- Adding persistence for pgAdmin using Development Docker
> Setting API-mobile communication

- .gitignore
Just tweaking needed folders to use Docker Compose
- Modified gitignore
- Added gitkeep files to track postgres and pgadmin persistence data folders
> Adding needed folders for Compose

- helpo-web/src/views/Actividades/ConsultarEventos/ConsultarEventosPage.js
Cuando no hay eventos, ahora se muestra un mensaje.
Es un mensaje feo, capaz podamos pensar en algo mejor y otra forma de mostrarlo, pero ya no se queda en cargando...
- Issue #95
> Issues varias

- docker-compose.yml
- helpo-web/src/views/Actividades/RegistrarEvento/SelectorUbicacion/SelectorUbicacion.js
- helpo-web/src/views/Pages/Register/Register.js
- Docker Compose now fetches changes within helpo-web container
- You can code and debug faster since JS changes autoreload
- Adding mail already signed up validation, issue #88 and #55 
- Behavior can be improved when email already exists
- Fixing minor JSX syntax mistakes
> Minor fixes including docker web autoreload and SignUp validation

- helpo-web/src/containers/DefaultLayout/DefaultHeader.js
- helpo-web/src/views/Perfiles/PerfilEmpresa/ModificarPerfilEmpresa.js
- helpo-web/src/views/Perfiles/PerfilOrganizacion/ModificarPerfilOrganizacion.js
- helpo-web/src/views/Perfiles/PerfilVoluntario/ModificarPerfilVoluntario.js
- Solucionado issue #83 
- El botón Volver del modal en Modificar Perfil vuelve a la consulta del perfil
- Solucionado issue #90 
- Se muestra el nombre del usuario al lado de la foto de perfil
https://github.com/Jumpi96/helpo/issues/83
https://github.com/Jumpi96/helpo/issues/90
Testing exploratorio
> Solucionado issue #83 & #90 - by @JuliRios

- README.md
Nueva tool para debugear mobile
-
-
-
> Agregue nueva tool

- helpo-web/src/views/Pages/Register/ModalRegistroExitoso.js
- helpo-web/src/views/Pages/Register/Register.js
-Solucionado issue #55 , falta hacerlo en mobile
https://github.com/Jumpi96/helpo/issues/55
Testing exploratorio
> Jrios bugfixes

- helpo-web/src/views/Actividades/RegistrarEvento/RegistrarEvento.js
- helpo-web/src/views/Pages/Register/Register.css
- helpo-web/src/views/Pages/Register/Register.js
- Solucionado issue #85 web, falta mobile
- Solucionado issue #77 front
https://github.com/Jumpi96/helpo/issues/85
https://github.com/Jumpi96/helpo/issues/77
Testing exploratorio
> Solucionado issue #85 web y #77 front

- helpo-web/src/views/Perfiles/PerfilEmpresa/ModificarPerfilEmpresa.js
- helpo-web/src/views/Perfiles/PerfilOrganizacion/ConsultarPerfilOrganizacion.js
- helpo-web/src/views/Perfiles/PerfilOrganizacion/ModificarPerfilOrganizacion.js
Está lleno de bugs todo lo que es modificar perfil, @Agianni21 faltaron ganas mepa
- Ahora se guardan cambios en el perfil de una ONG y de una Empresa
- Se descomentaron líneas para que Empresa no tire tantos errores
Ahora hay un poco menos de errores, no garantizo nada
- **FALTA MOBILE** (debería ser igual)
Issue #128 Modificar perfil - No se guardan los cambios
Exploratorios básicos (falta)
>  Issue #128: Modificar perfil ONG y Empresas web, falta mobile

- helpo-web/src/App.js
- helpo-web/src/routesNoAuth.js
- helpo-web/src/views/Actividades/ConsultarEventos/ConsultarEventosList.js
- helpo-web/src/views/Actividades/ConsultarEventos/ConsultarEventosView.js
- helpo-web/src/views/Actividades/ConsultarEventos/EventoCard/EventoCard.js
- helpo-web/src/views/Actividades/RedireccionarEvento/RedireccionarEvento.js
Mecanismo para compartir links de la plataforma que abra vista noAuth o auth segun corresponda.
- Link de redireccion para eventos: http://www.helpo.com.ar/#/redirect/evento?id=ID
- Boton ver más en noAuth
- #136 
Tests exploratorios
> Mecanismo de redireccion #136

- helpo-mobile/App/Services/Imagen.js
Agregue misma clase Imagen de web a mobile, usando AsyncStorage en vez de localStorage
Levante mobile y no crasheo.
> Agregado imagen para mobile

- helpo-web/public/index.html
> AWS for the Win

- helpo-api/actividades/services.py
- helpo-api/actividades/views.py
- helpo-api/common/templates.py
- helpo-api/templates/participacion-email.html
- helpo-mobile/App/api.js
Título
- 1 mail cuando se registra como voluntario con cierta función
- 1 mail cuando cancela
- 2 mails cuando modifica (1 cancela y 1 registra)
> Mail para Voluntario ante ABM participación como función en Evento

- helpo-api/actividades/serializers.py
> Serializer fix

- helpo-api/users/admin.py
- helpo-api/users/views.py
- helpo-web/src/utils/Imagen.js
- Agregue django-admin de appvalues (localhost:8000/admin, hace falta crear django superuser antes)
- Movi valores hardcodeados al .env
- Refactorize imagen.js y arregle un bug que hacia que se borre el token del localstorage
Tests Exploratorios
> Bugfix de imagenes

- helpo-mobile/App/Views/Actividades/ConsultarColaboraciones/ListaColaboraciones/DetalleColaboracion.js
- helpo-mobile/App/Views/Actividades/ConsultarColaboraciones/ListaColaboraciones/ListaColaboraciones.js
- helpo-mobile/App/Views/Actividades/ConsultarColaboraciones/ListaVoluntarios/DetalleParticipacion.js
- helpo-mobile/App/Views/Actividades/ConsultarColaboraciones/ListaVoluntarios/ListaVoluntarios.js
- helpo-mobile/App/api.js
- helpo-mobile/native-base-theme/variables/material.js
- Consulta colaboraciones mobile
- Font family iOS solved
- Sin basura :)
Exploratorio
> US-065 Consultar colaboraciones mobile 

- helpo-mobile/App/Containers/DrawerContent.js
- helpo-mobile/App/Views/Actividades/ConsultarEventos/EventoCard/EventoCard.js
- helpo-mobile/App/Views/Organizaciones/OrganizacionCard.js
- helpo-mobile/App/Views/Organizaciones/OrganizacionesPage.js
- helpo-web/src/routesEmpresa.js
- helpo-web/src/routesNoAuth.js
- helpo-web/src/routesOrganizacion.js
- helpo-web/src/routesVoluntario.js
- helpo-web/src/views/Actividades/ConsultarEventos/EventoCard/EventoCard.js
- helpo-web/src/views/Organizaciones/OrganizacionCard.js
- helpo-web/src/views/Organizaciones/OrganizacionesList.js
- helpo-web/src/views/Organizaciones/OrganizacionesPage.js
Mejoras de diseño y soluciones de routeo.
- Mejoras de diseño web y mobile.
- Problemas de routeo. 
- Nuevos routeos web.
Tests exploratorios.
> US-066 - Listado de ONGs RTC

- helpo-mobile/App/Navigation/NavigationDrawer.js
- helpo-mobile/App/Views/Actividades/RegistrarNecesidades/AgregarNecesidad/AgregarNecesidad.js
- helpo-mobile/App/Views/Actividades/RegistrarNecesidades/AgregarVoluntario/AgregarVoluntario.js
- helpo-mobile/App/Views/Actividades/RegistrarNecesidades/RegistrarNecesidades.js
- helpo-mobile/App/Views/Actividades/RegistrarNecesidades/styles.js
- helpo-mobile/App/Views/Actividades/RegistrarOfrecimiento/RegistrarOfrecimiento.js
- helpo-web/src/_navEmpresa.js
- helpo-web/src/_navOrganizacion.js
- helpo-web/src/_navVoluntario.js
- Opcion MisOrganizaciones para voluntarios, empresas y ong
- No crashea mas RegistrarOfrecimientos  en mobile
- Registrar necesidades anda en mobile
It's pre-demo day, what is testing?
> Bugfixes juampilorenzo

- helpo-mobile/ios/helpoMobile.xcodeproj/project.pbxproj
Solo necesito ese archivo, xfa
> Solo esto xfa

- helpo-mobile/App/Views/Actividades/MisPropuestas/VerPropuestaEvento.js
- Solved problemas con ComentarEvento en mobile
Exploratorios
> Minimal fix ComentarEvento

- helpo-mobile/App/Views/Actividades/MisPropuestas/VerPropuestaEvento.js
- First official release, made as a PoC
- Date: 09/18/2018
- Milestone: End of Sprint 10
- This is the first merge to release branch
- From now on, following releases will proceed as this one
> [RELEASE] Merging master to release v0.0.0

- helpo-api/Dockerfile
- helpo-api/actividades/management/commands/populate_db.py
- helpo-api/entrypoint.sh
- New command: python manage.py populate_db
- It automatically populates DB with initial data
- No more DB Prerequisites after this
- More data to be added
- Added to docker, suck it Bore
- **_Needs update in helpo-api .ENV_**
With my beautiful hands!
> SP-009: Adding DB auto-population with initial data

- helpo-web/src/views/Perfiles/ConsultarPerfilGenerico.js
- helpo-web/src/views/Perfiles/PerfilOrganizacion/ConsultarPerfilOrganizacion.js
…rio logeado
- Ahora solo puede modificar un perfil el usuario dueño del perfil
#180 
- Test exploratorio
> Bugfix issue #180

- helpo-web/src/views/Pages/ConfirmMail/FailedPresentation.js
- helpo-web/src/views/Pages/ConfirmMail/SuccessPresentation.js
- Redirección al Inicio de Sesión al verificar mail
> Corregida redirección a Iniciar Sesión

- helpo-web/src/views/Perfiles/ConsultarPerfilGenerico.js
- (Titulo)
- Test exploratorio
> Cambie el mensaje cuando se esta cargando el perfil - #210

- .gitignore
- docker-compose.aws.yml
- helpo-api/actividades/management/commands/categorias_recurso.csv
- helpo-api/actividades/management/commands/funciones_voluntario.csv
- helpo-api/actividades/management/commands/populate_db.py
- helpo-api/actividades/management/commands/rubros_empresa.csv
- helpo-api/actividades/management/commands/rubros_evento.csv
- helpo-api/actividades/management/commands/rubros_ong.csv
- helpo-api/entrypoint.sh
- helpo-api/helpo/settings/production.py
- helpo-api/helpo/urls.py
- Swagger disabled in production
- Added DB initial values
- Minor fixes
- **Implementing AWS RDS!!!**
Check AWS madafaka
> SP-009-quintus and last: AWS RDS!!

- helpo-web/src/routesEmpresa.js
- helpo-web/src/routesVoluntario.js
- helpo-web/src/views/Actividades/ConsultarEventos/AlbumImagenes/AlbumImagenes.js
- Agregue las rutas de Empresa y Voluntario
- Fix de bug visual en Album (Se ponia al costado la foto si hay una sola)
- Entre al album con voluntario, Empresa y ong
Issue #229
> Bugfix #229

- helpo-mobile/App/Views/Actividades/RegistrarEvento/RegistrarEvento.js
Para poder probar los eventos sin restriccion de fecha.
* Commit asquerosamente poco descriptivo:
* "Just this"
* [7045b3c](https://github.com/Jumpi96/helpo/pull/249/commits/7045b3c13459f0a68f44a2225df0f53172f1a79d)
> Fuera-validacion-evento-mobile: registrar en mismo dia

- helpo-mobile/App/Services/NavFunctions.js
- helpo-mobile/App/Views/Actividades/MisColaboraciones/VerColaboracionesEvento.js
- helpo-web/src/views/Actividades/MisColaboraciones/EventoView.js
Agregue boton para ir a "Ver Evento" desde "Mis Colaboraciones" en el voluntario, mas que
nada para que pueda acceder al album luego de finalizado el evento.
Test exploratorio (web y mobile)
> Boton "Ver Evento" en "Mis Colaboraciones"

- helpo-web/src/reducers/auth.js
Agregue un estado inicial en el redux de auth para usuarios no logeados
Test exploratorio local de pagina organizciones no logeado
> Listado Organizaciones bugfix

- helpo-mobile/.gitignore
- helpo-mobile/App/Services/NavFunctions.js
- helpo-mobile/App/Views/Actividades/ConsultarEventos/ConsultarEvento.js
- helpo-mobile/App/Views/Actividades/MisColaboraciones/VerColaboracionesEvento.js
- helpo-mobile/App/Views/Actividades/RegistrarColaboraciones/AgregarColaboracion.js
- helpo-mobile/App/Views/Actividades/RegistrarColaboraciones/RegistrarColaboraciones.js
- helpo-mobile/App/Views/Actividades/RegistrarEvento/RegistrarContacto/RegistrarContacto.js
- helpo-mobile/App/Views/Actividades/RegistrarEvento/RegistrarEvento.js
- helpo-mobile/App/Views/Actividades/RegistrarEvento/SelectorUbicacion/SelectorUbicacion.js
- helpo-mobile/App/Views/Actividades/RegistrarOfrecimiento/AgregarOfrecimiento.js
- helpo-mobile/App/Views/Actividades/VerEvento/VerEvento.js
- helpo-web/src/views/Actividades/ConsultarEventos/RegistrarColaboraciones/RegistrarColaboraciones.js
- helpo-web/src/views/Actividades/RegistrarOfrecimientos/RegistrarOfrecimientos.js
- Closes #171 
- Closes #226 
- Closes #244 
3 bugs críticos solved.
Tests explorativos.
> Bugfixes - Primer tanda #171 #226 #244

- docker-compose.local-base.aws.yml
- helpo-api/helpo/settings/production_local_base.py
- helpo-web/src/views/Perfiles/PerfilEmpresa/ConsultarPerfilEmpresa.js
- helpo-web/src/views/Perfiles/PerfilOrganizacion/ConsultarPerfilOrganizacion.js
- (instead of using real RDS production DB)
- Using local DB container at production, for testing purposes
- This configuration replaces RDS real production DB
- To use this, set new .ENV (check the wiki) and use docker-compose -f with new file
> [hot-fix-2] Adding new production with local DB configuration

- helpo-api/actividades/serializers.py
- helpo-api/actividades/services.py
- helpo-mobile/App/Views/Actividades/EditarEvento/EditarEvento.js
- helpo-mobile/App/Views/Actividades/MisEventos/MisEventos.js
- helpo-mobile/App/Views/Actividades/RegistrarEvento/RegistrarEvento.js
- helpo-mobile/App/Views/Actividades/VerEvento/VerEvento.js
- helpo-web/src/views/Actividades/ConsultarEventos/RegistrarColaboraciones/RegistrarColaboraciones.js
- helpo-web/src/views/Actividades/RegistrarOfrecimientos/RegistrarOfrecimientos.js
- Closes #250 
- Closes #104 
- Closes un bug importante en la api que encontre recien para actualizar evento (no solo mobile)
Me
> Bugfixes/juampilorenzo - Segunda tanda #250 #104

- helpo-api/actividades/serializers.py
- helpo-api/actividades/services.py
- helpo-api/actividades/views.py
- helpo-api/common/notifications.py
- helpo-mobile/App/Views/Actividades/RegistrarColaboraciones/AgregarColaboracion.js
- helpo-mobile/App/Views/Actividades/RegistrarColaboraciones/RegistrarColaboraciones.js
- helpo-mobile/App/Views/Actividades/RegistrarNecesidades/AgregarNecesidad/AgregarNecesidad.js
- helpo-mobile/App/Views/Actividades/RegistrarNecesidades/RegistrarNecesidades.js
- helpo-mobile/App/Views/Actividades/RegistrarOfrecimiento/AgregarOfrecimiento.js
- helpo-mobile/App/Views/Actividades/RegistrarOfrecimiento/RegistrarOfrecimiento.js
- helpo-web/src/views/Actividades/ConsultarEventos/RegistrarColaboraciones/RegistrarColaboraciones.js
- helpo-web/src/views/Actividades/RegistrarNecesidades/RegistrarNecesidades.js
- helpo-web/src/views/Actividades/RegistrarOfrecimientos/RegistrarOfrecimientos.js
- Ademas de eso arreglo unas cositas de JS
#240 y #167 
Me, myself and I
> Gulla-issues-2: Primera tanda #240 #167

- helpo-api/actividades/models.py
- helpo-api/users/serializers.py
- Title and yes, it's a stupid PR
- La cague ayudando a Juli con un objects.all(), tratando de ser mejor que Django, lo hago como antes
> Minor fixes to Strings functions and ONG getManos()

- helpo-mobile/App/Lib/Imagen.js
- helpo-mobile/App/Views/Actividades/ConsultarColaboraciones/ListaVoluntarios/ListaVoluntarios.js
- helpo-mobile/App/Views/Actividades/RegistrarColaboraciones/AgregarColaboracion.js
- helpo-web/src/utils/ImagenSelecter.js
- helpo-web/src/views/Actividades/ConsultarColaboraciones/TablaVoluntarios/TablaVoluntario.js
> Cosmetic issues #236 y #247

- helpo-web/src/scss/style.css
- helpo-web/src/views/Pages/Login/Login.js
- helpo-web/src/views/Pages/Register/Register.js
- helpo-web/src/views/Perfiles/PerfilOrganizacion/ConsultarPerfilOrganizacion.js
- Sign up y Sign in responsive
- Botones de redes sociales mejorados
> Login y Register responsive, botones de redes mejorados

- helpo-mobile/App/Views/Usuarios/Login.js
- helpo-mobile/App/Views/Usuarios/SignUp.js
- helpo-mobile/android/app/build.gradle
- Juan me dijo que tire PR de esto
- No se borraron los imports, asi que capaz falle algo en el proceso
Juan
> Bugfixes/juampilorenzo: commenting Google/FB signin at Mobile

- helpo-web/src/scss/_custom.scss
- helpo-web/src/scss/style.css
- helpo-web/src/views/Perfiles/PerfilEmpresa/ConsultarPerfilEmpresa.js
- helpo-web/src/views/Perfiles/PerfilEmpresa/ModificarPerfilEmpresa.js
- helpo-web/src/views/Perfiles/PerfilOrganizacion/ConsultarPerfilOrganizacion.js
- helpo-web/src/views/Perfiles/PerfilOrganizacion/ModificarPerfilOrganizacion.js
- helpo-web/src/views/Perfiles/PerfilVoluntario/ConsultarPerfilVoluntario.js
- helpo-web/src/views/Perfiles/PerfilVoluntario/ModificarPerfilVoluntario.js
> More bugsssssss #221 #256

- helpo-api/users/serializers.py
- Refactorización método getManos
> Refactorización de código

- helpo-web/prod.Dockerfile
> [hot-fix-3] Resolving PDF dependency at docker prod

- helpo-api/reportes/views.py
- helpo-web/src/_navOrganizacion.js
- helpo-web/src/views/Reportes/DashboardReportes.js
- Arregle query de eventos-manos
- Tildes
- Grafico de suscripciones con mes actual
Tests exploratorios
> US-081 - Dashboard - fixes de minuta Juli

- helpo-api/actividades/services.py
- helpo-api/actividades/signals/handlers.py
- helpo-api/common/templates.py
- helpo-api/reportes/views.py
- helpo-api/templates/creacion-evento-email.html
- helpo-mobile/App/Views/Perfiles/PerfilOrganizacion/ConsultarPerfilOrganizacion.js
- helpo-mobile/App/Views/Suscripciones/BotonSuscripcion/BotonDesubscribir.js
- helpo-mobile/App/Views/Suscripciones/BotonSuscripcion/BotonSuscribir.js
- helpo-mobile/App/Views/Suscripciones/MisSuscripciones/MisSuscripciones.js
- helpo-web/src/_navOrganizacion.js
- helpo-web/src/views/Reportes/DashboardReportes.js
- helpo-web/src/views/Suscripcion/BotonSuscripcion/BotonDesubscribir.js
- helpo-web/src/views/Suscripcion/BotonSuscripcion/BotonSubscribir.js
- helpo-web/src/views/Suscripcion/MisSuscripciones/MisSuscripciones.js
- Agrege las notificaciones por mail a los que esta suscriptos (Creacion y modificacion de evento)
- "Arregle el issue de suscripciones" (Me anda) #294
> "Fix" de suscripciones + Notificaciones #294

- helpo-mobile/App/Redux/ConsultarColabsRedux.js
- helpo-mobile/App/Views/Actividades/AlbumEvento/Album.js
- helpo-mobile/App/Views/Actividades/AlbumEvento/DetalleImagen.js
- helpo-mobile/App/Views/Actividades/ConsultarColaboraciones/ConsultarColaboraciones.js
- helpo-mobile/App/Views/Actividades/ConsultarColaboraciones/ListaColaboraciones/DetalleColaboracion.js
- helpo-mobile/App/Views/Actividades/ConsultarColaboraciones/ListaVoluntarios/DetalleParticipacion.js
- helpo-mobile/App/Views/Perfiles/PerfilOrganizacion/ConsultarPerfilOrganizacion.js
- helpo-mobile/App/Views/Perfiles/PerfilOrganizacion/ModificarPerfilOrganizacion.js
- helpo-mobile/App/Views/Suscripciones/BotonSuscripcion/ModalDesubscribir.js
- helpo-web/src/views/Actividades/ConsultarEventos/AlbumImagenes/ModalImagen.js
- helpo-web/src/views/Actividades/RegistrarEvento/RegistrarContacto/ModalEliminarItem.js
- helpo-web/src/views/Actividades/RegistrarNecesidades/ModalEliminarNecesidad/ModalEliminarNecesidad.js
- helpo-web/src/views/Perfiles/ConsultarPerfilGenerico.js
- helpo-web/src/views/Suscripcion/BotonSuscripcion/ModalDesubscribir.js
- helpo-web/src/views/common/ModalEliminarItem/ModalEliminarItem.js
* Validar campos (en ong/empresas no valida)
* Cambiar orden de campos ModificarPerfilOrganizacion
- (salen distintos a la consulta)
- Closes #211 
- Un par de errores de #290, pero no lo cierra al issue
#211 #290
Mucho
> gulla-issues-5: [PERFILES MOBILE] Issue #211 e issue #290

- helpo-api/common/templates.py
- helpo-api/templates/respuesta-propuesta.html
> Closes #301

- helpo-mobile/android/app/build.gradle
> Updating mobile version to 1.2.5, code 9

- helpo-mobile/App/Views/Perfiles/ConsultarPerfilGenerico.js
- helpo-mobile/App/Views/Perfiles/PerfilOrganizacion/ConsultarPerfilOrganizacion.js
- helpo-mobile/App/Views/Perfiles/PerfilOrganizacion/ModificarPerfilOrganizacion.js
- helpo-mobile/App/Views/Perfiles/PerfilVoluntario/ConsultarPerfilVoluntario.js
- helpo-mobile/App/Views/Perfiles/PerfilVoluntario/ModificarPerfilVoluntario.js
- Boton ver eventos  en mobile
- Se ve bien las descripciones largas en mobile
> Bugfixes perfiles

- helpo-web/src/utils/Imagen.js
- helpo-web/src/views/Actividades/ConsultarEventos/AlbumImagenes/ModalImagen.js
- Cambie como saco las dimensiones de la imagen en album web
Test exploratorio con 2 fotos (jpg y png)
> Agregue para que la imagen mantenga su aspect ratio

- helpo-api/actividades/management/commands/categorias_recurso.csv
-  Construcción,Arena,Baldes,Cemento,Mamelucos,Pinceles,Pintura,Otros
> Agregue construccion a rubro recursos

- helpo-api/actividades/management/commands/rubros_evento.csv
- ﻿Construcción
- Cultural
- Deportivo
- Educativo
- Recreativo
> Agrego construccion a rubro evento

- deploy_helpo.sh
- helpo-api/common/notifications.py
- helpo-mobile/App/Views/Actividades/AlbumEvento/GoAlbum.js
- helpo-mobile/App/Views/Actividades/EditarEvento/EditarEvento.js
- helpo-mobile/App/Views/Actividades/RegistrarEvento/RegistrarContacto/RegistrarContacto.js
- helpo-mobile/App/Views/Actividades/RegistrarEvento/RegistrarEvento.js
- helpo-mobile/App/Views/Actividades/VerEvento/VerEvento.js
- helpo-mobile/App/Views/Suscripciones/BotonSuscripcion/ModalDesubscribir.js
- helpo-mobile/App/Views/Usuarios/SignUp.js
- helpo-mobile/android/app/build.gradle
- helpo-web/src/views/Actividades/ConsultarEventos/AlbumImagenes/AlbumImagenes.js
- helpo-web/src/views/Actividades/ConsultarEventos/AlbumImagenes/ButtonGoAlbum.js
- helpo-web/src/views/Actividades/ConsultarEventos/AlbumImagenes/ModalImagen.js
- helpo-web/src/views/Actividades/ConsultarEventos/ConsultarEventosView.js
- helpo-web/src/views/Actividades/Eventos/EventoForm.js
- helpo-web/src/views/Actividades/Eventos/EventoView.js
- helpo-web/src/views/Actividades/RegistrarEvento/RegistrarContacto/ModalEditarItem.js
- helpo-web/src/views/Actividades/RegistrarEvento/RegistrarContacto/ModalEliminarItem.js
- helpo-web/src/views/Actividades/RegistrarEvento/RegistrarContacto/RegistrarContacto.js
- helpo-web/src/views/Actividades/RegistrarNecesidades/ModalEliminarNecesidad/ModalEliminarNecesidad.js
- helpo-web/src/views/Perfiles/ConsultarPerfilGenerico.js
- helpo-web/src/views/Suscripcion/BotonSuscripcion/ModalDesubscribir.js
- helpo-web/src/views/common/ModalEliminarItem/ModalEliminarItem.js
- Acentos al mandar notificaciones push con OneSignal
- Errores de ortografía issue #290 
- Corrección en la validación al registrar Contactos
- Ver un Evento hecho responsive en Web
Zombieeee
> gulla-issues-6: Push, Ortografía #290, Contactos y Responsive

- helpo-mobile/App/Views/Actividades/ConsultarEventos/ConsultarEvento.js
- helpo-mobile/App/Views/Perfiles/PerfilOrganizacion/ConsultarPerfilOrganizacion.js
- helpo-mobile/App/Views/Perfiles/PerfilVoluntario/ConsultarPerfilVoluntario.js
- helpo-mobile/android/app/build.gradle
- Title
- versionCode 11 and versionName 1.2.7
> Bugfixes/juampilorenzo: Fixing Perfiles Mobile and Descripciones largas

- helpo-api/common/templates.py
- helpo-api/templates/warning-email.html
- helpo-api/users/models.py
- helpo-api/users/serializers.py
- helpo-api/users/urls.py
- helpo-api/users/views.py
- helpo-mobile/App/Redux/AuthRedux.js
- helpo-mobile/App/Views/Usuarios/Configuracion.js
- helpo-mobile/App/Views/Usuarios/Login.js
- helpo-mobile/App/Views/Usuarios/SignUp.js
- helpo-mobile/android/app/build.gradle
- helpo-web/src/reducers/auth.js
- helpo-web/src/views/Pages/Login/Login.js
- helpo-web/src/views/Pages/Register/Register.js
- Si un usuario intenta iniciar sesión con una cuenta no verificada, se le da la posibilidad de solicitar que se le vuelva a enviar el correo de confirmación.
- Al registrar un nuevo usuario, se le avisa del envío del correo.
- Al registrar una nueva ONG o Empresa, se notifica a los administradores de Helpo.
- **FIX IMPORTANTE EN GOOGLE SIGNOUT MOBILE**
Web y Mobile, Sign in y Sign up manual/automático
> US-093: Hardening al registro de usuarios

- helpo-api/common/functions.py
- helpo-api/common/templates.py
- helpo-api/templates/change-password-email.html
- helpo-api/templates/creacion-evento-email.html
- helpo-api/templates/mensaje-evento.html
- helpo-api/templates/propuesta.html
- helpo-api/templates/reset-password-email.html
- helpo-api/users/serializers.py
- helpo-api/users/urls.py
- helpo-api/users/views.py
- helpo-mobile/App/Navigation/NavigationDrawer.js
- helpo-mobile/App/Views/Actividades/ConsultarEventos/ConsultarEventos.js
- helpo-mobile/App/Views/Organizaciones/OrganizacionesPage.js
- helpo-mobile/App/Views/Perfiles/PerfilOrganizacion/ConsultarPerfilOrganizacion.js
- helpo-mobile/App/Views/Usuarios/ChangePassword.js
- helpo-mobile/App/Views/Usuarios/Configuracion.js
- helpo-mobile/App/Views/Usuarios/Login.js
- helpo-mobile/App/Views/Usuarios/styles.js
- helpo-mobile/App/Views/Usuarios/stylesPassword.js
- helpo-web/src/containers/DefaultLayout/DefaultHeader.js
- helpo-web/src/routesEmpresa.js
- helpo-web/src/routesOrganizacion.js
- helpo-web/src/routesVoluntario.js
- helpo-web/src/views/Pages/Ajustes/AjustesPage.js
- helpo-web/src/views/Pages/Login/Login.js
- helpo-web/src/views/Pages/Register/Register.js
- Link a "¿Olvidaste tu contraseña?" en la pantalla de Login (al poner mal la password)
- En "Ajustes" (Web) y en "Configuración" (Mobile) se incluye la posibilidad de cambiar de contraseña
- Se envía mail tanto al resetear como al cambiar la contraseña
- Metí un par de fixes por distintos lados a la pasada
- Meto lo que faltaba para mostrar un tick en Mobile cuando las cuentas están verificadas
Local, web (responsive) y mobile, es igual para todos los user_types
> US-091: Recuperación y cambio de contraseña

- helpo-api/actividades/admin.py
- helpo-api/reportes/views.py
…s + Las agregue al django admin
- Cambie algunas de las queries dentro de las views de reportes
- Agregue Entregas y Presencias al django admin
Abri el dashboard ONG en web y mostraba lo mismo que habia en django admin, y abri el pdf
> Fix del Dashboard ONG (Bug explotador de campañas nuevas)

- helpo-mobile/App/Views/Perfiles/PerfilOrganizacion/ConsultarPerfilOrganizacion.js
- helpo-mobile/App/Views/Perfiles/PerfilOrganizacion/styles.js
- helpo-mobile/App/Views/Perfiles/PerfilVoluntario/ConsultarPerfilVoluntario.js
- helpo-mobile/App/Views/Perfiles/PerfilVoluntario/styles.js
- Terminada US-072
- Agregado de manos acumuladas y eventos en perfiles
Testing exploratorio
> Terminada US-072 mobile

- helpo-web/src/views/Actividades/ConsultarEventos/ConsultarEventosView.js
- El día se divide en dos renglones aún con resoluciones comunes.
> Bug en horarios en consultar evento

- helpo-web/src/views/Reportes/DashboardReportes.js
- Cambie la verificacion para descargar el PDF
> Bugfix - Alert en Dashboard ONG

- helpo-web/src/scss/style.css
> Se me genera esto todas las veces que buildeo

- helpo-api/actividades/models.py
- helpo-web/src/views/Actividades/MisPropuestas/EventoPage.js
- Really Closes #346
- Closes #348
> Arreglo Django Admin y cuando no hay propuestas #346 #348

- helpo-web/src/_navOrganizacion.js
- helpo-web/src/views/Recomendaciones/CargarEventoForm.js
- helpo-web/src/views/Recomendaciones/PanelRecomendacion.js
- helpo-web/src/views/Recomendaciones/PlanificadorEvento.js
- Fixes de Juli a la estetica de Web
> Cosmetica al front web de Planificar actividad

- helpo-api/common/functions.py
- No testee E2E lo de loguear la visita cuando estas offline, lo probe de formas en que HTTP_AUTHORIZATION pasa como None a python y desde el navegador pasa como "" --> explota consultar un solo evento deslogueado.
> Bug horrible en ConsultaEvento deslogueado

- helpo-api/users/urls.py
- helpo-api/users/views.py
- helpo-mobile/App/Containers/DrawerContent.js
- helpo-mobile/App/Navigation/NavigationDrawer.js
- helpo-mobile/App/Views/Empresas/EmpresasPage.js
- helpo-mobile/App/Views/Organizaciones/OrganizacionCard.js
- helpo-mobile/App/Views/Organizaciones/OrganizacionesPage.js
- helpo-web/src/_navEmpresa.js
- helpo-web/src/_navOrganizacion.js
- helpo-web/src/_navVoluntario.js
- helpo-web/src/containers/NoAuthLayout/NoAuthHeader.js
- helpo-web/src/routesEmpresa.js
- helpo-web/src/routesNoAuth.js
- helpo-web/src/routesOrganizacion.js
- helpo-web/src/routesVoluntario.js
- helpo-web/src/views/Empresas/EmpresasPage.js
- helpo-web/src/views/Organizaciones/OrganizacionesList.js
- helpo-web/src/views/Organizaciones/OrganizacionesPage.js
- Consultar empresas Web (auth/noAuth) y Mobile
- **Cambie el ORDEN de los botones de navegacion para los 3 usuarios en Web y Mobile**
No copie y pegue, viva yo
Web responsive con distintos actores y no auth, mobile tambien
> US-092: Listado de Empresas terminado

- helpo-api/actividades/services.py
- helpo-api/actividades/views.py
- helpo-api/common/templates.py
- helpo-api/templates/cambio-propuesta-email.html
- helpo-api/templates/creacion-evento-email.html
- helpo-api/templates/inicio-evento-email.html
- helpo-api/templates/propuesta.html
- helpo-mobile/App/Views/Actividades/MisPropuestas/ConfirmarEditarPropuesta.js
- helpo-web/src/views/Actividades/Eventos/EventoView.js
- helpo-web/src/views/Actividades/MisColaboraciones/EventoView.js
- helpo-web/src/views/Actividades/MisPropuestas/EventoPage.js
- helpo-web/src/views/Actividades/MisPropuestas/EventoView.js
- helpo-web/src/views/Actividades/MisPropuestas/ModalConfirmarEdicion.js
- helpo-web/src/views/Actividades/RegistrarEvento/RegistrarEvento.js
- helpo-web/src/views/Actividades/RegistrarEvento/SelectorHorarios/SelectorHorarios.js
- Si una Empresa cambia una propuesta aceptada hecha a una Campaña, mail y push a la ONG
- **Fix:** no se puede cambiar una propuesta aceptada a un Evento
- **Fix:** se agregan botones Compartir para Voluntario y Empresa
- Varios fixes cosméticos, sobre todo a mails y Actividades web (colaboraciones, patrocinios)
El que no descubrieron
Con 3 browsers uno con cada actor, como corresponde
> US-089: Notificar cambio en propuesta aceptada para Campaña

- helpo-api/actividades/management/commands/categorias_recurso.csv
> Muevo una fila para que queden bien los IDs

- helpo-api/recommendations/services.py
- helpo-api/recommendations/views.py
> Fixing ML first attempt with deployment

- helpo-mobile/App/Views/Actividades/RegistrarColaboraciones/RegistrarColaboraciones.js
- helpo-web/src/views/Actividades/ConsultarEventos/RegistrarColaboraciones/RegistrarColaboraciones.js
Fixes #340 
- Fixee un campo que estaba mal en la request desde el cliente
- En vez de PUT cambie por un PATCH cuando se actualiza una colaboracion
Test exploratorio en web
> Issue/#340 - Eliminar colaboracion borra el resto

- helpo-api/actividades/serializers.py
- helpo-api/actividades/views.py
- helpo-mobile/App/Redux/FiltroActividadesRedux.js
- helpo-mobile/App/Redux/index.js
- helpo-mobile/App/Views/Actividades/ConsultarEventos/ConsultarEventos.js
- helpo-mobile/App/Views/Actividades/ConsultarEventos/FiltroEventos/FiltroEventos.js
- helpo-mobile/App/Views/Actividades/MisColaboraciones/MisColaboraciones.js
- helpo-mobile/App/Views/Actividades/MisEventos/MisEventos.js
- helpo-mobile/App/Views/Actividades/MisPropuestas/MisPropuestas.js
- helpo-web/src/views/Actividades/ConsultarEventos/ConsultarEventosFilter.js
- helpo-web/src/views/Actividades/ConsultarEventos/ConsultarEventosList.js
- helpo-web/src/views/Actividades/ConsultarEventos/ConsultarEventosPage.js
- helpo-web/src/views/Actividades/Eventos/EventoList.js
- helpo-web/src/views/Actividades/MisColaboraciones/EventoList.js
- helpo-web/src/views/Actividades/MisPropuestas/EventoList.js
- Filtro en Consultar actividades (Logeado y no logeado)
- Filtro en Mis colaboraciones (Voluntario)
- Filtro en Mis patrocinios (Empresa)
- Filtro en Mis actividades (ONG)
Ahora no deberian aparecer en ninguna lista actividades que esten finalizadas, salvo que se aplique el filtro, y entonces aparecen todas juntas (finalizadas y no).
Cuando se pone el filtro en Consultar Actividades saco los separadores de actividades recomendadas (porque ya no estan en ese orden)
Test exploratorio
> Us 096 - Filtros actividades finalizadas

- helpo-web/src/views/Actividades/RegistrarEvento/RegistrarEvento.js
- Deshabilito el boton cuando comienza el submit, si validacion falla lo habilito de nuevo
- Closes #369 
-
Test exploratorio
> issue #369 - Multiples registros de AS

- helpo-mobile/App/Views/Actividades/ConsultarEventos/FiltroEventos/FiltroEventos.js
- helpo-web/src/views/Actividades/ConsultarEventos/ConsultarEventosFilter.js
> Deshabilite filtro "Acitivades Pasadas" en consultar actividades (Comente)

- helpo-web/src/routesNoAuth.js
closes #353 
- Agrege ruta para ver Album estando No Auth
-
-
Test exploratorio web
> Ruta para ver Album no auth

- helpo-mobile/android/app/build.gradle
- Updating helpo-mobile, versionCode 17 and versionName 1.4.2
> Updating helpo-mobile, versionCode 17 and versionName 1.4.2

- helpo-api/common/templates.py
closes #360 
- Descripcion en titulo
> Arregle un nombre en un mail (eventocampaña -> evento) - issue #360

- helpo-api/recommendations/views.py
- helpo-mobile/App/Views/Actividades/ConsultarEventos/ConsultarEventos.js
- helpo-web/src/views/Actividades/RegistrarNecesidades/RegistrarNecesidades.js
- Closes #387
- Closes #324 
- Mueve a low priority #334
> Bugs varios, cierre del día #324 #334 #387

- helpo-api/users/views.py
- (Titulo)
-
-
Test exploratorio en web (Pestaña Organizaciones) con un usuario ONG @machine.com
> Filtro en API para @machine.com (/perfiles/perfil_organizacion/)

- helpo-web/src/views/Perfiles/PerfilEmpresa/ConsultarPerfilEmpresa.js
closes #341 
- Arregle la alineacion de los botones
-
-
Test exploratorio web (empresa)
> #341 - Fix alineacion botones perfil empresa WEB

- helpo-mobile/App/Views/Actividades/RegistrarEvento/SelectorHorarios/SelectorHorarios.js
- helpo-web/src/views/Actividades/RegistrarEvento/SelectorHorarios/SelectorHorarios.js
- helpo-web/src/views/Perfiles/ConsultarPerfilGenerico.js
- Closes #345
- Nuevo diseño web
- Loader en perfiles web
> Bugfixes/juampilorenzo - Horarios 2.0 #345

- helpo-mobile/android/app/build.gradle
- Deploying helpo-mobile, versionCode 18 and versionName 1.4.3
> Deploying helpo-mobile, versionCode 18 and versionName 1.4.3

- helpo-mobile/App/Views/Actividades/RegistrarColaboraciones/RegistrarColaboraciones.js
- Faltaba la validacion de chequear que la nueva cantidad de la colaboracion no sea menor a la cantidad que estaba previamente entregada
-
-
Test exploratorio mobile
> Fix en Modificar colaboracion MOBILE - nueva cantidad < entregados

- helpo-mobile/App/Views/Actividades/MisColaboraciones/MisColaboraciones.js
- helpo-mobile/App/Views/Actividades/MisEventos/MisEventos.js
- helpo-mobile/App/Views/Actividades/MisPropuestas/MisPropuestas.js
- helpo-web/src/views/Actividades/Eventos/EventoList.js
- helpo-web/src/views/Actividades/MisColaboraciones/EventoList.js
- helpo-web/src/views/Actividades/MisPropuestas/EventoList.js
closes #189 
- Cambie el comportamiento del filtro de act finalizadas, ahora filtra las que tengan fecha/hora fin menor a fecha/hora actual.
- Agregue ordenamiento en las listas, de la misma forma que se ordenan en web
-
Test exploratorio web y mobile en c/componente
> Fix filtros act finalizadas - Ahora por fecha FIN

- helpo-mobile/App/Views/Actividades/ConsultarEventos/ConsultarEvento.js
- helpo-mobile/App/Views/Actividades/MisColaboraciones/MisColaboraciones.js
- helpo-mobile/App/Views/Actividades/MisEventos/MisEventos.js
- helpo-mobile/App/Views/Actividades/MisPropuestas/MisPropuestas.js
- helpo-mobile/App/Views/Actividades/VerEvento/VerEvento.js
- helpo-web/src/views/Actividades/ConsultarEventos/ConsultarEventosView.js
- helpo-web/src/views/Actividades/Eventos/EventoList.js
- helpo-web/src/views/Actividades/MisColaboraciones/EventoList.js
- helpo-web/src/views/Actividades/MisPropuestas/EventoList.js
- Para que aparezca el boton de album ahora se fija en fecha hora inicio del evento (si es mayor a fecha hora actual aparece)
- Agregue tilde en Álbum
-
Test exploratorio web y mobile
> Album no dependa de estado

- helpo-web/src/views/Actividades/ConsultarColaboraciones/downloadPDF.js
closes #425 
- (titulo)
-
-
Test exploratorio pdf
> Acomode el nombre de actividad en PDF colaboraciones

- helpo-mobile/App/Navigation/NavigationDrawer.js
closes #315 
- (titulo) 
- Ahora de albumEvento vuelve al componente que estaba antes (hace bien back)
-
Test exploratorio MOBILE como voluntario
> #315 - Saque AlbumEvento de NavigationDrawer, solo quedo en AppNavigation

- helpo-mobile/App/Views/Actividades/AlbumEvento/Album.js
- helpo-mobile/App/Views/Actividades/ConsultarEventos/ConsultarEvento.js
- helpo-mobile/App/Views/Actividades/EditarEvento/EditarEvento.js
- helpo-mobile/App/Views/Actividades/RegistrarColaboraciones/RegistrarColaboraciones.js
- helpo-mobile/App/Views/Actividades/VerEvento/VerEvento.js
- helpo-web/src/views/Actividades/ConsultarEventos/ConsultarEventosView.js
- helpo-web/src/views/Actividades/Eventos/EventoForm.js
- helpo-web/src/views/Actividades/Eventos/EventoView.js
> Bugfixes/juampilorenzo - Varios

- helpo-api/actividades/serializers.py
- helpo-api/actividades/services.py
- helpo-api/common/templates.py
- helpo-api/templates/propuesta.html
- Closes #302 y saca envio de mail "Registro colaboracion" a Empresa #358
- Empresas no reciben mas mails cuando **CREAN** Colaboraciones o Participaciones, si cuando las **editan** o **eliminan**
#302 #358
> Closes #302 y saca envio de mail "Registro colaboracion" a Empresa #358

- helpo-mobile/App/Views/Actividades/RegistrarEvento/RegistrarEvento.js
- helpo-web/src/views/Actividades/ConsultarEventos/RegistrarColaboraciones/RegistrarColaboraciones.js
> Un par mas #369 #376

- helpo-api/common/notifications.py
- helpo-web/src/containers/DefaultLayout/DefaultHeader.js
- helpo-web/src/views/Reportes/DashboardReportes.js
- Ver commit messages
- Mails entre 30 y 40 seg, probar
> gulla-issues-1: Campanita y fast mails

- helpo-mobile/App/Views/Actividades/ConsultarColaboraciones/ConsultarColaboraciones.js
- helpo-web/src/views/Actividades/ConsultarEventos/RegistrarColaboraciones/RegistrarColaboraciones.js
- helpo-web/src/views/Perfiles/PerfilEmpresa/ConsultarPerfilEmpresa.js
- helpo-web/src/views/Perfiles/PerfilOrganizacion/ConsultarPerfilOrganizacion.js
- helpo-web/src/views/Perfiles/PerfilVoluntario/ConsultarPerfilVoluntario.js
> Bugfixes/juampilorenzo #388 #426

- helpo-mobile/android/app/build.gradle
- Deploying helpo-mobile versionCode 20 and versionName 1.4.5
> [MOBILE] Deploying helpo-mobile versionCode 20 and versionName 1.4.5

- helpo-api/reportes/views.py
> PR estado reporte

- helpo-mobile/App/Views/Actividades/RegistrarNecesidades/AgregarNecesidad/AgregarNecesidad.js
- helpo-mobile/App/Views/Actividades/RegistrarNecesidades/AgregarVoluntario/AgregarVoluntario.js
- helpo-mobile/App/Views/Actividades/RegistrarNecesidades/RegistrarNecesidades.js
- helpo-web/src/views/Actividades/RegistrarNecesidades/RegistrarNecesidades.js
closes #334 
- Validacion en registrar necesidades para no poder repetir funciones/necesidades (web y mobile)
-
-
Test exploratorio web y mobile
> Issue/#334 - Registrar necesidades - Funcion/Necesidades repetidas

- helpo-web/src/containers/NoAuthLayout/NoAuthLayout.js
closes #397 
- Fuerzo a que el contenedor main no tenga margenes a la izquierda
-
-
Test exploratorio web chrome
> #397 - Fix de al deslogearte queda un margen a la izquierda

- helpo-web/src/containers/DefaultLayout/DefaultHeader.js
- helpo-web/src/routesEmpresa.js
- helpo-web/src/routesNoAuth.js
- helpo-web/src/routesOrganizacion.js
- helpo-web/src/routesVoluntario.js
- helpo-web/src/views/Actividades/ConsultarEventos/ConsultarEventosView.js
- helpo-web/src/views/Actividades/ConsultarEventos/RegistrarColaboraciones/RegistrarColaboraciones.js
- helpo-web/src/views/Actividades/Redirecciones/RedireccionarEvento.js
- helpo-web/src/views/Widgets/Widget02.js
- Closes #321
- Closes #436
- Closes #251
> Fixes varios

- helpo-web/src/views/Actividades/RegistrarEvento/RegistrarContacto/RegistrarContacto.js
closes #367 
- Cambie como se inicializa la variable del error para que no se acumulen
-
-
Test exploratorio web
> Modifique como se modificaba el error - ahora no se acumula

- helpo-web/src/views/Actividades/RegistrarEvento/RegistrarContacto/ModalEditarItem.js
closes #232 
- Agrande los campos en editar contacto
- Arregle como acumula errores
-
Test exploratorio
> Mejores campos en editar contacto

- helpo-mobile/App/Views/Actividades/ComentarEvento/ComentarEvento.js
- Mejora diseño, nuevos mensajes de ayuda
Closes #449
> [Mobile] ComentarEvento

- helpo-mobile/App/Views/Actividades/RegistrarColaboraciones/RegistrarColaboraciones.js
- helpo-mobile/android/app/build.gradle
> [MOBILE] Mobile 1.5.1

- collect_logs.sh
- helpo-api/helpo/settings/production.py
- helpo-api/helpo/settings/production_local_base.py
- Changing logging to files
- Adding script to collect logs
> Gulla issues: logging tweaks

- .circleci/config.yml
- .github/workflows/aws.yml
- helpo-api/requirements.txt
- helpo-api/task-definition.json
- helpo-web/Dockerfile
- helpo-web/package.json
- helpo-web/prod.Dockerfile
- Integrate helpo-api with AWS ECS using GitHub Actions 
Needs integration test
> #458 - Integrate helpo-api with AWS ECS using GitHub Actions

- README.md
- deploy_helpo.sh
- helpo-api/Dockerfile
- helpo-api/entrypoint.sh
- API Dockerfile refactored
- Cosmetic
> Feature/docker-n-tweaks: Helpo-api Dockerfile and Readme

- helpo-web/prod.Dockerfile
- Add git to helpo-web docker image
> Feature/git-en-web to Master: Add git to helpo-web docker image

- .github/ISSUE_TEMPLATE/helpo-issue-template.md
> Adapting issue to USs and bugs

- helpo-web/src/containers/NoAuthLayout/NoAuthFooter.js
- helpo-web/src/views/Home/HomeNoAuth.js
- Close #489
- No delta with `helpo-mobile`
#489 
Not tested at all
> Close #489: Update email and FB page

- helpo-api/actividades/views.py
- helpo-api/recommendations/services.py
- helpo-api/recommendations/views.py
> Hotfix pre-interview

- helpo-web/src/views/Home/HomeNoAuth.js
- Close #496
Commenting code, pure love.
#496 
Localhost and about to deploy it to PROD
> Close #496: Remove Twitter and FB timelines/feeds

- helpo-web/src/views/Home/HomeNoAuth.js
- Close #505
- #505
Localhost, Ctrl+F5, Firefox
> Modificado títulos y textos de cards de página de inicio

- helpo-web/public/index.html
> Adding analytics

- deploy_helpo.sh
- deploy_helpo_aws.sh
- For Juan. With love, Gonzalo
> Preventing my CTO from crying everytime he deploys

- helpo-web/src/_navVoluntario.js
- helpo-web/src/containers/NoAuthLayout/NoAuthHeader.js
- helpo-web/src/views/Home/HomeNoAuth.js
> v.1.2 - Mejoras esteticas finales 

- deploy_helpo_aws_staging.sh
- deploy_helpo_staging.sh
- docker-compose.local-base.aws.staging.yml
- docker-compose.staging.yml
- helpo-api/helpo/settings/staging_local_base.py
- helpo-web/nginx-staging.conf
- helpo-web/nginx.conf
- helpo-web/staging.Dockerfile
- Staging ENV 
- Cache expiration to 1d
In our brand new staging ENV!!
> Feature/staging_n_cache: Staging env and cache expiration of static assets

- backup_local-base_aws.sh
- Backup script
- <https://github.com/Jumpi96/helpo/wiki/DB-Backups>
Production and Staging
> Feature/db backups: Backups not working

- backup_local-base_aws.sh
> N-th Fix for DB backups

- .gitignore
- deploy_helpo.sh
- helpo-web/nginx-staging.conf
- helpo-web/nginx.conf
- No era este el error igual... no te voy a contar la huevada que estaba haciendo
> Cache control back to DNS level

- helpo-api/helpo/settings/staging_local_base.py
- helpo-web/public/index.html
- Closes #547 
- May also close #545, depending on @Grego
> Closes #547 and relates to #545

- helpo-web/src/containers/DefaultLayout/DefaultLayout.js
- helpo-web/src/scss/style.css
> Footer corrido de lugar al regresar a página principal

- helpo-web/src/containers/NoAuthLayout/NoAuthFooter.js
- helpo-web/src/views/Actividades/ConsultarColaboraciones/ConsultarColaboraciones.js
- helpo-web/src/views/Home/HomeNoAuth.js
- helpo-web/src/views/Pages/Register/Register.js
- helpo-web/src/views/Perfiles/PerfilOrganizacion/ModificarPerfilOrganizacion.js
- Agregado de ícono de whatsapp en footer
- Modificación de mensaje de éxito de modal
- Quitado de "" en Misión y Visión
- Modifcado ONG por Organización social en Registro
- Alineado label Ubicación en consulta de perfil ONG
#552 
- Local
> Modificaciones cosméticas varias

- helpo-api/templates/ong-colaboracion-email.html
- helpo-api/templates/ong-participacion-email.html
- helpo-api/templates/was-ong-colaboracion-email.html
- helpo-api/templates/was-ong-participacion-email.html
> 550 - Adding more information to emails

- helpo-api/Dockerfile
- helpo-api/logrotate.conf
- helpo-api/send_logs_s3.sh
> Adding logrotate

- helpo-api/users/models.py
- helpo-api/users/views.py
- helpo-web/src/scss/_custom.scss
- helpo-web/src/scss/style.css
- helpo-web/src/views/Voluntarios/VoluntariosFilter.js
- helpo-web/src/views/Voluntarios/VoluntariosList.js
> #559 - Agregar paginación a listado de voluntarios

- helpo-api/users/views.py
> Fixing voluntarios bug

- helpo-web/src/views/Pages/Login/Login.js
- helpo-web/src/views/Pages/Register/Register.js
- Mejora UX ante error de comunicacion
- Manual: registro exitoso y registro de email ya existente
- Manual tirando la API en el momento de la consulta
> Mejora - Bug en registro
